# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='policy',
            options={'ordering': ('name',), 'verbose_name_plural': 'policies'},
        ),
        migrations.AlterModelOptions(
            name='policymember',
            options={'ordering': ('region', 'ip__hostname')},
        ),
        migrations.AlterField(
            model_name='policymember',
            name='region',
            field=models.CharField(choices=[('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('ap-northeast-2', 'Asia Pacific (Seoul)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('ca-central-1', 'Canada (Central)'), ('cn-north-1', 'China (Beijing)'), ('eu-central-1', 'EU (Frankfurt)'), ('eu-west-1', 'EU (Ireland)'), ('eu-west-2', 'EU (London)'), ('sa-east-1', 'South America (São Paulo)')], default='us-east-1', max_length=20),
        ),
    ]
