# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 13:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0002_auto_20170309_1144'),
        ('zinc', '0002_zone_ns_propagated'),
    ]

    operations = [
    ]
