# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-15 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import zinc.models


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0003_zone_ns_propagated'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='cached_ns_records',
            field=models.TextField(default=None, null=True, validators=[zinc.models.validate_json]),
        ),
    ]
