# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0004_merge_20170306_1138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policymember',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_members', to='dns.IP'),
        ),
    ]
