# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0005_policymember_enabled'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='zone',
            options={'ordering': ['root']},
        ),
    ]
