# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0006_auto_20170414_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='routing',
            field=models.CharField(choices=[('latency', 'latency'), ('weighted', 'weighted')], default='latency', max_length=255),
        ),
    ]
