# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-02-28 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zinc', '0008_set_routing_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecord',
            name='record_type',
            field=models.CharField(choices=[('A', 'A'), ('AAAA', 'AAAA')], default='A', max_length=10),
        ),
        migrations.AlterField(
            model_name='ip',
            name='ip',
            field=models.GenericIPAddressField(primary_key=True, serialize=False, verbose_name='IP Address'),
        ),
        migrations.AlterField(
            model_name='policymember',
            name='region',
            field=models.CharField(choices=[('af-south-1', 'Africa (Cape Town)'), ('ap-east-1', 'Asia Pacific (Hong Kong)'), ('ap-northeast-1', 'Asia Pacific (Tokyo)'), ('ap-northeast-2', 'Asia Pacific (Seoul)'), ('ap-northeast-3', 'Asia Pacific (Osaka-Local)'), ('ap-south-1', 'Asia Pacific (Mumbai)'), ('ap-southeast-1', 'Asia Pacific (Singapore)'), ('ap-southeast-2', 'Asia Pacific (Sydney)'), ('ap-southeast-3', 'Asia Pacific (Jakarta)'), ('ca-central-1', 'Canada (Central)'), ('cn-north-1', 'China (Beijing)'), ('cn-northwest-1', 'China (Ningxia)'), ('eu-central-1', 'Europe (Frankfurt)'), ('eu-north-1', 'Europe (Stockholm)'), ('eu-south-1', 'Europe (Milan)'), ('eu-west-1', 'Europe (Ireland)'), ('eu-west-2', 'Europe (London)'), ('eu-west-3', 'Europe (Paris)'), ('me-south-1', 'Middle East (Bahrain)'), ('sa-east-1', 'South America (São Paulo)'), ('us-east-1', 'US East (N. Virginia)'), ('us-east-2', 'US East (Ohio)'), ('us-west-1', 'US West (N. California)'), ('us-west-2', 'US West (Oregon)')], default='us-east-1', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='policyrecord',
            unique_together=set([('name', 'record_type', 'zone')]),
        ),
    ]
