build:
  zinc:
    image: presslabs/zinc
    pull: true
    auth_config:
      username: presslabsbot
      password: $$DOCKER_PASSWORD
      email: ping@presslabs.com
    environment:
      - BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - ONCE_REDIS_URL=redis://redis:6379/2
      - DJANGO_SETTINGS_MODULE=zinc.settings
    commands:
      - pip install -U -r requirements/test.txt
      - py.test --capture=no --tb=native

compose:
  redis:
    image: redis

publish:
  docker:
    username: presslabsbot
    password: $$DOCKER_PASSWORD
    email: ping@presslabs.com
    repo: presslabs/zinc
    tag: $${BRANCH/master/latest}
    when:
      event: push
