build:
  zinc:
    image: presslabs/zinc
    pull: true
    auth_config:
      username: presslabsbot
      password: $$DOCKER_PASSWORD
      email: ping@presslabs.com
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings.test
      - ZINC_AWS_KEY=$$ZINC_AWS_KEY
      - ZINC_AWS_SECRET=$$ZINC_AWS_SECRET
    commands:
      - pip install -U -r requirements.dev.txt
      - make lint
      - make full-test

publish:
  docker:
    username: presslabsbot
    password: $$DOCKER_PASSWORD
    email: ping@presslabs.com
    repo: presslabs/zinc
    tag: $${BRANCH/master/latest}
    storage_path: /drone/docker
    when:
      branch: master

cache:
  mount:
    - /drone/docker
