---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: test
  pull: always
  image: python:3.5
  commands:
  - pip install -U -r requirements.dev.txt
  - make lint
  - make full-test
  environment:
    DJANGO_SETTINGS_MODULE: django_project.settings.test
    ZINC_AWS_KEY:
      from_secret: ZINC_AWS_KEY
    ZINC_AWS_SECRET:
      from_secret: ZINC_AWS_SECRET
    ZINC_SECRET_KEY: not-so-secret

- name: publish-docker-image
  pull: if-not-exists
  image: plugins/docker
  settings:
    build_args:
    - release="${DRONE_COMMIT_SHA:0:7}"
    repo: presslabs/zinc
    tags:
    - ${DRONE_BRANCH/master/latest}
    - ${DRONE_COMMIT_SHA:0:7}
    username: presslabsbot
    password:
      from_secret: DOCKERHUB_TOKEN

---
kind: signature
hmac: c2ed22603cc391065b72613db36006619bbaf4e6f8676c4cc8a06651d92e34c5

...
