pipeline:
  test:
    image: python:3.5
    pull: true
    environment:
      - DJANGO_SETTINGS_MODULE=django_project.settings.test
      - ZINC_SECRET_KEY=not-so-secret
    commands:
      - pip install -U -r requirements.dev.txt
      - make lint
      - make full-test
    secrets:
      - ZINC_AWS_KEY
      - ZINC_AWS_SECRET
    volumes:
      - '/var/lib/drone/cache/pip:/root/.cache/pip'

  publish-docker-image:
    image: plugins/docker
    repo: presslabs/zinc
    tags: ["${DRONE_BRANCH/master/latest}", "${DRONE_COMMIT_SHA:0:7}"]
    build_args:
      - release="${DRONE_COMMIT_SHA:0:7}"
    secrets:
      - docker_username
      - docker_password
