build:
  zinc:
    image: presslabs/zinc
    pull: true
    auth_config:
      username: presslabsbot
      password: $$DOCKER_PASSWORD
      email: ping@presslabs.com
    environment:
      - BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/1
      - ONCE_REDIS_URL=redis://redis:6379/2
      - DJANGO_SETTINGS_MODULE=zinc.test_settings
    commands:
      - pip install -U -r requirements.dev.txt
      - pep8 --max-line-length=100 --exclude=migrations .
      - py.test --capture=no --tb=native -k 'not with_aws'

compose:
  redis:
    image: redis

publish:
  docker:
    username: presslabsbot
    password: $$DOCKER_PASSWORD
    email: ping@presslabs.com
    repo: presslabs/zinc
    tag: $${BRANCH/master/latest}
    storage_path: /drone/docker
    when:
      event: push

cache:
  mount:
    - /drone/docker
