version: '2'
services:
    zinc:
        build: .
        volumes:
            - .:/app
        command: dockerize -wait tcp://redis:6379 -timeout 30s ./manage.py runserver 0.0.0.0:8000
        depends_on:
            - redis
        ports:
            - "8000:8000"
    celery:
        build: .
        command: dockerize -wait tcp://redis:6379 -timeout 30s celery worker --autoreload -A zinc.vendors.celery -l info
        volumes:
            - .:/app
        depends_on:
            - redis
    redis:
        image: redis