[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "django_project.settings.test"
norecursedirs = "contrib"
testpaths = [ "tests", ]

[tool.ruff]
line-length = 120
exclude = [ "tests", ]


[tool.ruff.per-file-ignores]
"**/tests/*" = ["F811"]