# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-12 12:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, protocol='IPv4', serialize=False, verbose_name='IP Address')),
                ('provider', models.CharField(max_length=128)),
                ('name', models.CharField(max_length=24, verbose_name='Name')),
                ('location', models.CharField(max_length=32, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='ManagedRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('record_type', models.CharField(default='POLICY_ROUTED', editable=False, max_length=13)),
                ('value', models.TextField()),
                ('ttl', models.IntegerField(validators=[django.core.validators.MinValueValidator(300)])),
                ('dirty', models.BooleanField(default=True, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('modified_index', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name_plural': 'policies',
            },
        ),
        migrations.CreateModel(
            name='PolicyMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthcheck_id', models.IntegerField(editable=False, null=True)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('location', models.CharField(choices=[('us-east-1', 'us-east-1'), ('us-west-1', 'us-west-1'), ('us-west-2', 'us-west-2'), ('ap-northeast-1', 'ap-northeast-1'), ('ap-northeast-2', 'ap-northeast-2'), ('ap-south-1', 'ap-south-1'), ('ap-southeast-1', 'ap-southeast-1'), ('ap-southeast-2', 'ap-southeast-2'), ('sa-east-1', 'sa-east-1'), ('eu-west-1', 'eu-west-1'), ('eu-central-1', 'eu-central-1')], max_length=10)),
                ('ip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.IP')),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('root', models.CharField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_root_domain', message='Invalid root domain', regex='[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\\.(?!-)[a-z0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.$')])),
                ('aws_id', models.IntegerField(editable=False)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Policy')),
            ],
        ),
        migrations.AddField(
            model_name='policy',
            name='members',
            field=models.ManyToManyField(to='dns.PolicyMember'),
        ),
    ]
