# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 12:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IP',
            fields=[
                ('ip', models.CharField(max_length=40, primary_key=True, serialize=False, validators=[django.core.validators.validate_ipv46_address], verbose_name=b'IP Address')),
                ('server_name', models.CharField(max_length=255)),
                ('healthcheck_id', models.IntegerField(editable=False, null=True)),
                ('weight', models.PositiveIntegerField(default=10)),
                ('location', models.CharField(choices=[(b'us', b'US')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('modified_index', models.PositiveIntegerField(default=0, editable=False)),
                ('ip', models.ManyToManyField(to='dns.IP')),
            ],
            options={
                'verbose_name_plural': 'policies',
            },
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.CharField(max_length=255, unique=True)),
                ('aws_id', models.IntegerField(editable=False)),
                ('dirty', models.BooleanField(default=False, editable=False)),
                ('records', models.TextField(default=b'[]')),
            ],
        ),
        migrations.AddField(
            model_name='domain',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Policy'),
        ),
        migrations.AddField(
            model_name='domain',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Zone'),
        ),
    ]
