# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-18 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='usable',
            field=models.BooleanField(default=True),
        ),
    ]
