# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='caller_reference',
            field=models.UUIDField(editable=False, unique=True),
        ),
    ]
