# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 09:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dirty', models.BooleanField(default=True, editable=False)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Policy')),
            ],
        ),
        migrations.DeleteModel(
            name='ManagedRecord',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='location',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='name',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='aws_id',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='name',
        ),
        migrations.RemoveField(
            model_name='zone',
            name='policy',
        ),
        migrations.AddField(
            model_name='ip',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='friendly_name',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='hostname',
            field=models.CharField(default='', max_length=64, validators=[django.core.validators.RegexValidator(code='invalid_hostname', message='Invalid hostname', regex='^(?=[a-z0-9\\-\\.]{1,253}$)([a-z0-9](([a-z0-9\\-]){,61}[a-z0-9])?\\.)*([a-z0-9](([a-z0-9\\-]){,61}[a-z0-9])?)$')]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='zone',
            name='route53_id',
            field=models.CharField(default='', editable=False, max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policymember',
            name='location',
            field=models.CharField(choices=[('us-east-1', 'us-east-1'), ('us-west-1', 'us-west-1'), ('us-west-2', 'us-west-2'), ('ap-northeast-1', 'ap-northeast-1'), ('ap-northeast-2', 'ap-northeast-2'), ('ap-south-1', 'ap-south-1'), ('ap-southeast-1', 'ap-southeast-1'), ('ap-southeast-2', 'ap-southeast-2'), ('sa-east-1', 'sa-east-1'), ('eu-west-1', 'eu-west-1'), ('eu-central-1', 'eu-central-1')], max_length=20),
        ),
        migrations.AlterField(
            model_name='zone',
            name='root',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_root_domain', message='Invalid root domain', regex='[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\\.(?!-)[a-z0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)$')]),
        ),
        migrations.AddField(
            model_name='policyrecord',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dns.Zone'),
        ),
    ]
