# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-03 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0002_ip_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='caller_reference',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
