# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-02 14:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0002_ip_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyrecord',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dns.Policy'),
        ),
    ]
