# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-02 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0002_auto_20160826_1148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='modified_index',
        ),
        migrations.AlterField(
            model_name='zone',
            name='caller_reference',
            field=models.CharField(editable=False, max_length=32, unique=True),
        ),
    ]
