# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-17 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0003_auto_20161102_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', editable=False, min_length=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='policymember',
            name='id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', editable=False, min_length=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='policyrecord',
            name='id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', editable=False, min_length=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='policyrecord',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
