# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-06 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0003_auto_20170302_1415'),
        ('dns', '0003_auto_20170303_1722'),
    ]

    operations = [
    ]
