# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0004_auto_20170117_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='policymember',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dns.Policy'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='members',
            field=models.ManyToManyField(related_name='old_policy', to='dns.PolicyMember'),
        ),
    ]
