# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 21:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0005_auto_20170306_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ip',
            options={'verbose_name': 'IP'},
        ),
    ]
