# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 13:39
from __future__ import unicode_literals

from django.db import migrations


def copy_policy(apps, schema_editor):
    # We can't import the model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    PolicyMember = apps.get_model("dns", "PolicyMember")
    for member in PolicyMember.objects.all():
        member.policy = member.old_policy.first()
        member.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0005_auto_20170127_1338'),
    ]

    operations = [
        migrations.RunPython(copy_policy),
    ]
