# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-27 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0007_auto_20170127_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policymember',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='dns.Policy'),
        ),
    ]
