# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0010_auto_20170131_0743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policyrecord',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
