# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0011_auto_20170131_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='policymember',
            old_name='location',
            new_name='region',
        ),
        migrations.AlterField(
            model_name='policyrecord',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_records', to='dns.Zone'),
        ),
    ]
