# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 12:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0012_auto_20170203_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='ip',
            name='healthcheck_caller_reference',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='ip',
            name='healthcheck_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
