# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 15:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0012_auto_20170203_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='policyrecord',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='policyrecord',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='zone',
            name='root',
            field=models.CharField(max_length=255, validators=[django.core.validators.RegexValidator(code='invalid_root_domain', message='Invalid root domain', regex='[a-z0-9](?:[a-z0-9-]{0,61}[a-z0-9])?(?:\\.(?!-)[a-z0-9-]{1,63}(?<!-))*\\.(?!-)(?:[a-z-]{2,63}|xn--[a-z0-9]{1,59})(?<!-)\\.?$')]),
        ),
        migrations.AlterUniqueTogether(
            name='policyrecord',
            unique_together=set([('name', 'zone')]),
        ),
    ]
