# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-14 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0013_auto_20170209_1201'),
        ('dns', '0013_auto_20170208_1547'),
    ]

    operations = [
    ]
