# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-15 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0014_merge_20170214_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='deleted',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
