# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 10:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0015_zone_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zone',
            name='caller_reference',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='zone',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='zone',
            name='route53_id',
            field=models.CharField(default=None, editable=False, max_length=32, null=True, unique=True),
        ),
    ]
